#!/command/with-contenv sh
# shellcheck shell=sh

set -eu
if [ -z "${RELAY:-}" ]; then
  echo "RELAY must be set to the externally reachable relay host:port" >&2
  exit 64
fi

cd /data
exec s6-setuidgid nobody /usr/bin/hbbs -r "$RELAY" -k _
